ci: add parallel test coverage calculation
fastify/fastify-basic-auth pull request #29
Opened 2021-03-09 10:41 UTC by Fdawgs

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-03-09 10:58 UTC, Fdawgs commented on .github/workflows/ci.yml
> +          npm run license-checker --if-present
Removed with https://github.com/fastify/fastify-basic-auth/pull/29/commits/79266ca35a168121ffa4f7acc2ff63da8c87699c

2021-03-09 11:00 UTC, mcollina approved these changes
lgtm

2021-03-09 11:05 UTC, mcollina commented
It seems that coveralls is configured by not working.

2021-03-09 11:05 UTC, mcollina requested changes
CI is failing because coveralls is not setup correctly or something.

2021-03-09 11:10 UTC, Fdawgs commented
> 
> 
> CI is failing because coveralls is not setup correctly or something.

It looks okay and is using the same config as the main Fastify repo and other Fastify plugin repos.
I think it may be related to what you raised in https://github.com/fastify/fastify-accepts-serializer/pull/37#discussion_r590209007

2021-03-09 13:55 UTC, mcollina requested changes

2021-03-09 13:55 UTC, mcollina commented on package.json
> +    "test:ci": "standard && tap -J test.js --coverage-report=lcovonly && tsd"
This change is not needed anymore.

2021-03-09 13:55 UTC, mcollina commented on .github/workflows/ci.yml
> +          npm run test:ci
```suggestion
          npm run test
```

2021-03-09 13:58 UTC, mcollina commented
> > 
> 
> > 
> 
> > CI is failing because coveralls is not setup correctly or something.
> 
> 
> 
> It looks okay and is using the same config as the main Fastify repo and other Fastify plugin repos.
> 
> I think it may be related to what you raised in https://github.com/fastify/fastify-accepts-serializer/pull/37#discussion_r590209007

It's likely related. Enabling coveralls or analog for all repos requires significant work, so better avoid it entirely.

2021-03-09 13:58 UTC, mcollina commented
The main Fastify repo is a special/ snowflake case.

2021-03-10 17:01 UTC, mcollina approved these changes
lgtm

2021-03-10 17:01 UTC, merged