Added Error to return type of async validator
fastify/fastify-basic-auth pull request #89
Opened 2022-05-03 20:57 UTC by vjau

This PR changes the Typescript definition.
When using an async validator, errors are either throwed or returned.
The initial typing only considered the case when Error where throwed. This PR add a union type including Error on the returned Promise.
The test is also modified by returning an Error

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-05-03 21:01 UTC, vjau commented
Sorry, i have seen that there is already a pending PR addressing what this PR is doing. #58 
However, #58 is more ambitious (i have actually tried to do what #58 try to do the whole day without success), i think this more limited fix could be merged for now. 
Thank you.

2022-05-03 21:47 UTC, climba03003 requested changes

2022-05-03 21:47 UTC, climba03003 commented on index.test-d.ts
> +    return new Error("unauthorized")
Can you split it in separate test? So, it test both `void` and `Error`.

2022-05-04 09:12 UTC, vjau commented
I have splitted the test as requested

2022-05-04 09:14 UTC, mcollina approved these changes
lgtm

2022-05-04 09:22 UTC, climba03003 approved these changes
LGTM.

2022-05-04 09:29 UTC, merged